

 const datapackege=[
    {
        id:1,
        title:"chennai to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Rameshwaram","Kodaikanal","Ooty","Kumbakonam","Madurai","Kanyakumari","Yercaud","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"The distance between Chennai and Rameshwaram is approximately 570 to 600 kilometers, depending on the route taken. The travel distance might vary based on the specific starting and ending points within the two cities the road journey from Chennai to Rameshwaram takes approximately 10 to 11 hours by car or bus, depending on the traffic conditions, road quality, and the route taken. The route usually involves traveling along National Highway 45 and then branching off to reach Rameshwaram.",
        d1train:"There are direct train services available from Chennai to Rameshwaram. The train journey takes around 10 to 12 hours, depending on the specific train and its schedule.",
        d1air:"The nearest airport to Rameshwaram is Madurai Airport. You can take a flight from Chennai to Madurai, which takes around 1 to 1.5 hours, and then proceed to Rameshwaram by road, which would take additional time",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"The road journey from Chennai to Kodaikanal takes approximately 9 to 10 hours by bus or car, depending on the traffic conditions, road quality, and the route taken. The route typically involves traveling through cities like Madurai or Dindigul before reaching Kodaikanal.",
        d2train:"There is no direct train route from Chennai to Kodaikanal. You can take a train from Chennai to Madurai or Dindigul, which are the nearest major railheads to Kodaikanal. From there, you would need to take a bus or taxi to reach Kodaikanal, which would add a few more hours to your travel time.",
        d2air:"The nearest airport to Kodaikanal is Madurai Airport. You can take a flight from Chennai to Madurai, and then proceed to Kodaikanal by road, which would take additional time.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"The distance between Chennai and Kumbakonam is approximately 280 to 320 kilometers.The road journey from Chennai to Kumbakonam takes approximately 5 to 6 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d3train:"There are direct train services available from Chennai to Kumbakonam. The train journey takes around 5 to 6 hours, depending on the specific train and its schedule.",
        d3air:"The nearest airport to Kumbakonam is Tiruchirapalli International Airport (Trichy). You can take a flight from Chennai to Trichy (approximately 1-hour flight), and then continue your journey to Kumbakonam by road, which would take additional time.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"The distance between Chennai and Ooty is approximately 540 to 600 kilometers. The road journey from Chennai to Ooty takes approximately 10 to 11 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken. The route often involves traveling through cities like Coimbatore or Mettupalayam before reaching Ooty.",
        d3train:"There is no direct train route to Ooty. The nearest major railway station is Mettupalayam. From there, you can board the Nilgiri Mountain Railway, a UNESCO World Heritage Site, which takes you on a scenic journey uphill to Ooty. The train journey adds a unique experience to your travel and takes about 5 hours.",
        d3air:"There are no direct flights to Ooty. The nearest airport is Coimbatore International Airport. You can take a flight from Chennai to Coimbatore (approximately 1-hour flight), and then continue your journey to Ooty by road or train, which would take additional time.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"The distance between Chennai and Kumbakonam is approximately 280 to 320 kilometers.The road journey from Chennai to Kumbakonam takes approximately 5 to 6 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d4train:"The road journey from Chennai to Kumbakonam takes approximately 5 to 6 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d4air:"The nearest airport to Kumbakonam is Tiruchirapalli International Airport (Trichy). You can take a flight from Chennai to Trichy (approximately 1-hour flight), and then continue your journey to Kumbakonam by road, which would take additional time.",
        d5roadhed:"By Road (Bus/Car)",
        d5trainhed:"By Train:",
        d5airhed:"By Air:",
        d5road:"The distance between Chennai and Madurai is approximately 450 to 500 kilometers.The road journey from Chennai to Madurai takes approximately 7 to 8 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d5train:"There are direct train services available from Chennai to Madurai. The train journey takes around 6 to 8 hours, depending on the specific train and its schedule.",
        d5air:"You can take a flight from Chennai to Madurai, which is a convenient option. The flight duration is approximately 1 hour.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"The distance between Chennai and Kanyakumari is approximately 650 to 700 kilometers.The road journey from Chennai to Kanyakumari takes approximately 12 to 14 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d6train:"There are direct train services available from Chennai to Kanyakumari. The train journey takes around 14 to 16 hours, depending on the specific train and its schedule",
        d6air:"The nearest airport to Kanyakumari is Trivandrum International Airport. You can take a flight from Chennai to Trivandrum (approximately 1-hour flight), and then continue your journey to Kanyakumari by road, which would take additional time.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"The distance between Chennai and Yercaud is approximately 370 to 400 kilometers.The road journey from Chennai to Yercaud takes approximately 6 to 7 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d7train:"There are no direct train services to Yercaud. You can take a train from Chennai to Salem, which is the nearest major railway station to Yercaud. From Salem, Yercaud is about a 1-hour drive.",
        d7air:"The nearest airport to Yercaud is Salem Airport. You can take a flight from Chennai to Salem (approximately 1-hour flight), and then proceed to Yercaud by road.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:" The distance between Chennai and Theni is approximately 480 to 530 kilometers.The road journey from Chennai to Theni takes approximately 8 to 9 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d8train:"There are no direct train services to Theni. You can take a train from Chennai to a nearby city like Madurai or Dindigul, and then continue your journey to Theni by road.",
        d8air:"The nearest airport to Theni is Madurai Airport. You can take a flight from Chennai to Madurai (approximately 1-hour flight), and then proceed to Theni by road.",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"The distance between Chennai and Hogenakkal is approximately 300 to 350 kilometers.The road journey from Chennai to Hogenakkal takes approximately 6 to 7 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken",
        d9train:"There are no direct train services to Hogenakkal. You can take a train from Chennai to Dharmapuri, which is the nearest major railway station to Hogenakkal. From Dharmapuri, Hogenakkal is about a 1-hour drive.",
        d9air:"The nearest airport to Hogenakkal is Salem Airport. You can take a flight from Chennai to Salem (approximately 1-hour flight), and then continue to Hogenakkal by road.",
        
    },
    {
        id:2,
        title:"Rameshwaram to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Kodaikanal","Ooty","Kumbakonam","Madurai","Kanyakumari","Yercaud","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"The distance between Rameshwaram and Chennai is approximately 570 to 600 kilometers.The road journey from Rameshwaram to Chennai takes approximately 10 to 11 hours by car or bus, depending on factors such as traffic conditions, road quality, and the specific route taken.",
        d1train:"There are direct train services available from Rameshwaram to Chennai. The train journey takes around 10 to 12 hours, depending on the specific train and its schedule",
        d1air:"The nearest airport to Rameshwaram is Madurai Airport. You can travel from Rameshwaram to Madurai by road (around 3 hours), and then take a flight from Madurai to Chennai (approximately 1-hour flight).",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"Approximate distance by road: 300 to 350 kilometers The road journey from Rameshwaram to Kodaikanal takes approximately 9 to 10 hours by car or bus. The route typically involves traveling through cities like Madurai or Dindigul before reaching Kodaikanal.",
        d2train:"There are no direct train services from Rameshwaram to Kodaikanal. You can take a train from Rameshwaram to Madurai, and then proceed to Kodaikanal by road, which would take additional time.",
        d2air:"There are no direct flights from Rameshwaram to Kodaikanal. The nearest airport to Kodaikanal is Madurai Airport. You can travel from Rameshwaram to Madurai by road (around 3 hours), and then explore Kodaikanal.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"Approximate distance by road: 500 to 550 kilometers The road journey from Rameshwaram to Ooty takes approximately 13 to 14 hours by car or bus. The route usually involves traveling through cities like Madurai and Coimbatore before reaching Ooty.",
        d3train:"There are no direct train services from Rameshwaram to Ooty. You can take a train from Rameshwaram to Coimbatore, and then proceed to Ooty by road or Nilgiri Mountain Railway, which is a scenic train journey.",
        d3air:"There are no direct flights from Rameshwaram to Ooty. The nearest airport to Ooty is Coimbatore Airport. You can travel from Rameshwaram to Coimbatore by road or train, and then continue to Ooty.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"Approximate distance by road: 220 to 250 kilometers The road journey from Rameshwaram to Kumbakonam takes approximately 6 to 7 hours by car or bus. The route involves traveling through cities like Madurai and Tanjore before reaching Kumbakonam.",
        d4train:"There are train services available from Rameshwaram to Kumbakonam with a changeover at Madurai. The journey takes around 10 to 12 hours.",
        d4air:"There are no direct flights from Rameshwaram to Kumbakonam. You can travel to nearby Trichy Airport by road or train from Rameshwaram, and then proceed to Kumbakonam.",
        
        d5roadhed:"By Road (Bus/Car)",
        d5trainhed:"By Train:",
        d5airhed:"By Air:",
        d5road:"Approximate distance by road: 170 to 200 kilometers  The road journey from Rameshwaram to Madurai takes approximately 3 to 4 hours by car or bus.",
        d5train:"There are direct train services available from Rameshwaram to Madurai. The train journey takes around 3 to 4 hours.",
        d5air:"There are no direct flights from Rameshwaram to Madurai. The nearest airport to Rameshwaram is Madurai Airport itself.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"Approximate distance by road: 300 to 350 kilometers The road journey from Rameshwaram to Kanyakumari takes approximately 5 to 6 hours by car or bus. The route involves traveling through cities like Tirunelveli before reaching Kanyakumari.",
        d6train:"There are train services available from Rameshwaram to Kanyakumari with a changeover at Mandapam. The journey takes around 6 to 7 hours.",
        d6air:"There are no direct flights from Rameshwaram to Kanyakumari. The nearest airport to Kanyakumari is Trivandrum International Airport. You can travel from Rameshwaram to Trivandrum by road (around 4 hours), and then proceed to Kanyakumari.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Approximate road distance: 450 to 500 kilometers. The road journey takes approximately 8 to 9 hours, depending on traffic and specific route.",
        d7train:"There are no direct train services from Rameshwaram to Yercaud. You would need to take a train to nearby Salem or Erode and then continue your journey to Yercaud by road.",
        d7air:"There are no direct flights from Rameshwaram to Yercaud. The nearest airport to Yercaud is Coimbatore Airport. You can travel from Rameshwaram to Coimbatore by road or train and then proceed to Yercaud.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:" Approximate road distance: 270 to 320 kilometers. The road journey takes approximately 5 to 6 hours, depending on traffic and specific route.",
        d8train:"There are train services available from Rameshwaram to Theni with a changeover at Madurai. The journey takes around 8 to 9 hours.",
        d8air:"There are no direct flights from Rameshwaram to Theni. The nearest airport to Theni is Madurai Airport. You can travel from Rameshwaram to Madurai by road (around 3 hours) and then proceed to Theni.",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:" Approximate road distance: 250 to 300 kilometers. The road journey takes approximately 6 to 7 hours, depending on traffic and specific route.",
        d9train:" There are no direct train services from Rameshwaram to Hogenakkal. You can take a train to Dharmapuri or Salem, and then continue your journey to Hogenakkal by road.",
        d9air:"There are no direct flights from Rameshwaram to Hogenakkal. The nearest airport to Hogenakkal is Salem Airport. You can travel from Rameshwaram to Salem by road or train and then proceed to Hogenakkal.",
        

    },
    {
        id:3,
        title:"Kodaikanal to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Ooty","Kumbakonam","Madurai","Kanyakumari","Yercaud","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"Approximate road distance: 520 to 570 kilometers.Road journey duration: Approximately 10 to 11 hours.",
        d1train:"There are no direct train services from Kodaikanal to Chennai. You would need to travel by road to a nearby railway station like Kodai Road or Dindigul, and then take a train to Chennai.",
        d1air:"There are no direct flights from Kodaikanal to Chennai. The nearest airport to Kodaikanal is Madurai Airport. You can travel from Kodaikanal to Madurai by road (around 3 to 4 hours), and then take a flight to Chennai.",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"Approximate road distance: 320 to 360 kilometers.Road journey duration: Approximately 6 to 7 hours.",
        d2train:"There are no direct train services from Kodaikanal to Rameshwaram. You can travel by road to a nearby railway station like Madurai, and then take a train to Rameshwaram.",
        d2air:"There are no direct flights from Kodaikanal to Rameshwaram. The nearest airport to Rameshwaram is Madurai Airport. You can travel from Kodaikanal to Madurai by road (around 3 to 4 hours) and then proceed to Rameshwaram.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"Approximate road distance: 280 to 320 kilometers.Road journey duration: Approximately 7 to 8 hours.",
        d3train:"There are no direct train services from Kodaikanal to Ooty. You can travel by road to a nearby railway station like Coimbatore, and then proceed to Ooty by road or the Nilgiri Mountain Railway.",
        d3air:"There are no direct flights from Kodaikanal to Ooty. The nearest airport to Ooty is Coimbatore Airport. You can travel from Kodaikanal to Coimbatore by road and then continue to Ooty.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"Approximate road distance: 390 to 430 kilometers.Road journey duration: Approximately 8 to 9 hours.",
        d4train:"There are no direct train services from Kodaikanal to Kumbakonam. You can travel by road to a nearby railway station like Dindigul or Trichy, and then take a train to Kumbakonam",
        d4air:"There are no direct flights from Kodaikanal to Kumbakonam. You can travel from Kodaikanal to Trichy Airport by road and then proceed to Kumbakonam.",
        d5trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"Approximate road distance: 120 to 150 kilometers.Road journey duration: Approximately 3 to 4 hours.",
        d5train:"There are no direct train services from Kodaikanal to Madurai. You can travel by road to a nearby railway station like Kodai Road, and then take a train to Madurai.",
        d5air:"There are no direct flights from Kodaikanal to Madurai. The nearest airport to Kodaikanal is Madurai Airport.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"Approximate road distance: 300 to 350 kilometers.Road journey duration: Approximately 7 to 8 hours.",
        d6train:"There are no direct train services from Kodaikanal to Kanyakumari. You can travel by road to a nearby railway station like Madurai or Nagercoil, and then take a train to Kanyakumari.",
        d6air:"There are no direct flights from Kodaikanal to Kanyakumari. The nearest airport to Kanyakumari is Trivandrum International Airport. You can travel from Kodaikanal to Trivandrum by road and then proceed to Kanyakumari.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Approximate road distance: 220 to 260 kilometers.Road journey duration: Approximately 5 to 6 hours.",
        d7train:"There are no direct train services from Kodaikanal to Yercaud. You can travel by road to a nearby railway station like Salem, and then proceed to Yercaud.",
        d7air:"There are no direct flights from Kodaikanal to Yercaud. The nearest airport to Yercaud is Salem Airport. You can travel from Kodaikanal to Salem by road and then explore Yercaud.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:"Approximate road distance: 90 to 120 kilometers.Road journey duration: Approximately 2 to 3 hours.",
        d8train:"There are no direct train services from Kodaikanal to Theni. You can travel by road to a nearby railway station like Dindigul, and then take a train to Theni.",
        d8air:"There are no direct flights from Kodaikanal to Theni. The nearest airport to Theni is Madurai Airport. You can travel from Kodaikanal to Madurai by road and then proceed to Theni",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"Approximate road distance: 300 to 350 kilometers.Road journey duration: Approximately 6 to 7 hours.",
        d9train:"There are no direct train services from Kodaikanal to Hogenakkal. You can travel by road to a nearby railway station like Dharmapuri or Salem, and then proceed to Hogenakkal.",
        d9air:"",
    },
    {
        id:4,
        title:"Ooty to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Kodaikanal","Kumbakonam","Madurai","Kanyakumari","Yercaud","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"Ooty to Chennai: The distance between Ooty and Chennai is 462 kilometers. The road trip takes about 8 hours 30 minutes via NH48.",
        d1train:"There are several trains that travel from Ooty to Chennai. The fastest train is the Nilgiri Express, which takes about 6 hours 30 minutes.",
        d1air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore Airport to Chennai",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"Ooty to Rameswaram: The distance between Ooty and Rameswaram is 802 kilometers. The road trip takes about 13 hours 30 minutes via NH48 and NH7.",
        d2train:"There are no direct trains from Ooty to Rameswaram. You will have to take a train to Madurai and then change trains to Rameswaram. The total journey time is about 12 hours.",
        d2air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore Airport to Madurai, which is the gateway to Rameswaram.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"Approximate road distance: 65 kilometers Road journey duration: Approximately 1 hour 30 minutes",
        d3train:"There are no direct trains from Ooty to Kodaikanal. You will have to take a train to Coimbatore and then change trains to Kodaikanal. The total journey time is about 2 hours.",
        d3air:"There is no airport in Kodaikanal. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore Airport to Kodaikanal.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"Approximate road distance: 425 kilometers Road journey duration: Approximately 7 hours 30 minutes",
        d4train:"There are several trains that travel from Ooty to Kumbakonam. The fastest train is the Nilgiri Express, which takes about 7 hours.",
        d4air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore Airport to Kumbakonam.",
        d5trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"Approximate road distance: 373 kilometers Road journey duration: Approximately 6 hours",
        d5train:"There are several trains that travel from Ooty to Madurai. The fastest train is the Nilgiri Express, which takes about 6 hours.",
        d5air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore Airport to Madurai.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"Approximate road distance: 621 kilometers Road journey duration: Approximately 10 hours",
        d6train:"There are no direct trains from Ooty to Kanyakumari. You will have to take a train to Madurai and then change trains to Kanyakumari. The total journey time is about 10 hours.",
        d6air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore Airport to Madurai, which is the gateway to Kanyakumari.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Approximate road distance: 90 to 120 kilometers Road journey duration: Approximately 2 to 3 hours",
        d7train:"There are no direct trains from Ooty to Yercaud. You will have to take a train to Coimbatore and then change trains to Yercaud. The total journey time is about 2 hours.",
        d7air:"There is no airport in Yercaud. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore Airport to Yercaud",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:"Approximate road distance: 225 kilometers Road journey duration: Approximately 4 hours",
        d8train:"There are several trains that travel from Ooty to Theni. The fastest train is the Nilgiri Express, which takes about 4 hours.",
        d8air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore International Airport to Theni.",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"Approximate road distance: 270 kilometers Road journey duration: Approximately 5 hours",
        d9train:"There are no direct trains from Ooty to Hogenakkal. You will have to take a train to Salem or Dindigul and then change trains to Hogenakkal. The total journey time is about 6 hours.",
        d9air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore International Airport to Salem or Dindigul. From there, you can take a taxi or bus to Hogenakkal.",
    },
    {
        id:5,
        title:"Kumbakonam to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Kodaikanal","Ooty","Madurai","Kanyakumari","Yercaud","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"Approximate road distance: 290 kilometers Road journey duration: Approximately 5 hours",
        d1train:"There are several trains that travel from Kumbakonam to Chennai. The fastest train is the Vaigai Express, which takes about 4 hours.",
        d1air:"There is no airport in Kumbakonam. The nearest airport is Trichy International Airport, which is about 50 kilometers away. There are several flights from Trichy International Airport to Chennai.",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"Approximate road distance: 350 kilometers Road journey duration: Approximately 6 hours",
        d2train:"There are several trains that travel from Kumbakonam to Rameswaram. The fastest train is the Vaigai Express, which takes about 5 hours.",
        d2air:"There is no airport in Kumbakonam. The nearest airport is Trichy International Airport, which is about 50 kilometers away. There are several flights from Trichy International Airport to Madurai, which is the gateway to Rameswaram.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"Approximate road distance: 190 kilometers Road journey duration: Approximately 3 hours",
        d3train:"There are no direct trains from Kumbakonam to Kodaikanal. You will have to take a train to Coimbatore and then change trains to Kodaikanal. The total journey time is about 4 hours.",
        d3air:"There is no airport in Kodaikanal. The nearest airport is Coimbatore International Airport, which is about 150 kilometers away. There are several flights from Coimbatore International Airport to Kodaikanal.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"Approximate road distance: 250 kilometers Road journey duration: Approximately 4 hours",
        d4train:"There are no direct trains from Kumbakonam to Ooty. You will have to take a train to Coimbatore and then change trains to Ooty. The total journey time is about 5 hours.",
        d4air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 100 kilometers away. There are several flights from Coimbatore International Airport to Ooty.",
        d5trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"Approximate road distance: 180 kilometers Road journey duration: Approximately 3 hours",
        d5train:"There are several trains that travel from Kumbakonam to Madurai. The fastest train is the Vaigai Express, which takes about 2 hours.",
        d5air:"There is no airport in Kumbakonam. The nearest airport is Trichy International Airport, which is about 50 kilometers away. There are several flights from Trichy International Airport to Madurai",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"Approximate road distance: 320 kilometers Road journey duration: Approximately 5 hours",
        d6train:"There are several trains that travel from Kumbakonam to Kanyakumari. The fastest train is the Vaigai Express, which takes about 4 hours.",
        d6air:"There is no airport in Kumbakonam. The nearest airport is Trichy International Airport, which is about 50 kilometers away. There are several flights from Trichy International Airport to Madurai, which is the gateway to Kanyakumari.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Approximate road distance: 200 kilometers Road journey duration: Approximately 3 hours",
        d7train:"There are no direct trains from Kumbakonam to Yercaud. You will have",
        d7air:"The travel time from Kumbakonam to Yercaud by air is approximately 2 hours 30 minutes, plus the time it takes to get from Salem to Yercaud.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:"Approximate road distance: 150 kilometers Road journey duration: Approximately 2 hours 30 minutes [Image of Kumbakonam to Theni road trip]",
        d8train:"There are several trains that travel from Kumbakonam to Theni. The fastest train is the Vaigai Express, which takes about 2 hours.",
        d8air:"There is no airport in Kumbakonam. The nearest airport is Trichy International Airport, which is about 50 kilometers away. There are several flights from Trichy International Airport to Madurai. From Madurai, you can take a taxi or bus to Theni.",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"Approximate road distance: 180 kilometers Road journey duration: Approximately 3 hours [Image of Kumbakonam to Hogenakkal road trip]",
        d9train:"There are no direct trains from Kumbakonam to Hogenakkal. You will have to take a train to Salem or Dindigul and then change trains to Hogenakkal. The total journey time is about 4 hours.",
        d9air:"There is no airport in Hogenakkal. The nearest airport is Salem International Airport, which is about 70 kilometers away. There are several flights from Salem International Airport to Salem. From Salem, you can take a taxi or bus to Hogenakkal.",
    },
    {
        id:6,
        title:"Madurai to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Kodaikanal","Ooty","Kumbakonam","Kanyakumari","Yercaud","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"Approximate road distance: 455 kilometers Road journey duration: Approximately 7 hours 30 minutes",
        d1train:"There are several trains that travel from Madurai to Chennai. The fastest train is the Vaigai Express, which takes about 6 hours.",
        d1air:"Madurai International Airport is located about 15 kilometers from the city center. There are several flights from Madurai International Airport to Chennai International Airport. The flight time is about 1 hour 15 minutes.",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"Approximate road distance: 265 kilometers Road journey duration: Approximately 5 hours",
        d2train:"There are several trains that travel from Madurai to Rameswaram. The fastest train is the Rameswaram Express, which takes about 4 hours.",
        d2air:"There is no airport in Rameswaram. The nearest airport is Madurai International Airport. There are several flights from Madurai International Airport to Rameswaram. The flight time is about 1 hour.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"Approximate road distance: 285 kilometers Road journey duration: Approximately 5 hours 30 minutes:",
        d3road:"There are no direct trains from Madurai to Kodaikanal. You will have to take a train to Madurai and then change trains to Kodaikanal. The total journey time is about 7 hours.",
        d3train:"There are no direct trains from Madurai to Kodaikanal. You will have to take a train to Madurai and then change trains to Kodaikanal. The total journey time is about 7 hours",
        d3air:"Madurai International Airport is located about 15 kilometers from the city center. There are several flights from Madurai International Airport to Madurai Airport. The flight time is about 1 hour 15 minutes. From Madurai Airport, you can take a taxi or bus to Kodaikanal. The taxi fare is around 600 and the bus fare is around 100 The bus journey takes about 2 hours.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"Approximate road distance: 460 kilometers Road journey duration: Approximately 8 hours",
        d4train:"There are no direct trains from Madurai to Ooty. You will have to take a train to Madurai and then change trains to Ooty. The total journey time is about 10 hours.",
        d4air:"Madurai International Airport is located about 15 kilometers from the city center. There are several flights from Madurai International Airport to Madurai Airport. The flight time is about 1 hour 15 minutes. From Madurai Airport, you can take a taxi or bus to Ooty. The taxi fare is around 600 and the bus fare is around 100 The bus journey takes about 2 hours.",
        d5trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"Approximate road distance: 170 kilometers Road journey duration: Approximately 3 hours",
        d5train:"There are several trains that travel from Madurai to Kumbakonam. The fastest train is the Vaigai Express, which takes about 2 hours.",
        d5air:"Madurai International Airport is located about 15 kilometers from the city center. There are several flights from Madurai International Airport to Trichy International Airport. From Trichy International Airport, you can take a taxi or bus to Kumbakonam. The taxi fare is around 600 and the bus fare is around 100 The bus journey takes about 1 hour.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"Approximate road distance: 630 kilometers Road journey duration: Approximately 10 hours",
        d6train:"There are several trains that travel from Madurai to Kanyakumari. The fastest train is the Kanyakumari Express, which takes about 8 hours.",
        d6air:"Madurai International Airport is located about 15 kilometers from the city center. There are several flights from Madurai International Airport to Thiruvananthapuram International Airport, which is the nearest airport to Kanyakumari. The flight time is about 1 hour.Ticket fare: Around INR 1,500 to 3,000 for a one-way economy class ticket",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Approximate road distance: 200 kilometers Road journey duration: Approximately 3 hours",
        d7train:"There are no direct trains from Madurai to Yercaud. You will have to take a train to Salem and then change trains to Yercaud. The total journey time is about 4 hours.Ticket fare: Around INR 500 to 1,000 for a sleeper class ticket and INR 1,000 to 1,500 for a AC class ticket",
        d7air:"You are right. There are no airports in Yercaud, Thenni, and Hogenakkal. The nearest airport to Yercaud is Coimbatore International Airport, which is about 160 kilometers away. The nearest airport to Thenni is Madurai International Airport, which is about 150 kilometers away. The nearest airport to Hogenakkal is Salem International Airport, which is about 70 kilometers away.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:"Approximate road distance: 150 kilometers Road journey duration: Approximately 2 hours 30 minutes",
        d8train:"There are no direct trains from Madurai to Thenni. You will have to take a train to Dindigul and then change trains to Thenni. The total journey time is about 4 hours.Ticket fare: Around INR 500 to 1,000 for a sleeper class ticket and INR 1,000 to 1,500 for a AC class tickett",
        d8air:"Fly to Madurai International Airport Take a taxi or bus to Thenni",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"Approximate road distance: 180 kilometersRoad journey duration: Approximately 3 hours",
        d9train:"There are no direct trains from Madurai to Hogenakkal. You will have to take a train to Salem or Dindigul and then change trains to Hogenakkal. The total journey time is about 4 hours.",
        d9air:"Fly to Madurai International Airport Take a taxi or bus to Salem Take a taxi or bus to Hogenakkal",
    },
    {
        id:7,
        title:"Kanyakumari to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Kodaikanal","Ooty","Kumbakonam","Madurai","Yercaud","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"Approximate road distance: 630 kilometers Road journey duration: Approximately 10 hours",
        d1train:"There are several trains that travel from Kanyakumari to Chennai. The fastest train is the Kanyakumari Express, which takes about 8 hours. ",
        d1air:"There is no airport in Kanyakumari. The nearest airport is Thiruvananthapuram International Airport, which is about 120 kilometers away. There are several flights from Thiruvananthapuram International Airport to Chennai International Airport. The flight time is about 30 minutes.",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"Approximate road distance: 630 kilometers Road journey duration: Approximately 10 hours",
        d2train:"There are several trains that travel from Kanyakumari to Rameswaram. The fastest train is the Kanyakumari Express, which takes about 8 hours.",
        d2air:"There is no airport in Rameswaram. The nearest airport is Madurai International Airport, which is about 120 kilometers away. There are several flights from Madurai International Airport to Rameswaram Airport. The flight time is about 1 hour.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"Approximate road distance: 200 kilometers Road journey duration: Approximately 3 hours",
        d3train:"There are no direct trains from Kanyakumari to Kodaikanal. You will have to take a train to Coimbatore and then change trains to Kodaikanal. The total journey time is about 5 hours.",
        d3air:"There is no airport in Kodaikanal. The nearest airport is Coimbatore International Airport, which is about 160 kilometers away. There are several flights from Coimbatore International Airport to Madurai Airport. The flight time is about 1 hour. From Madurai Airport, you can take a taxi or bus to Kodaikanal. The taxi fare is around INR 200 and the bus fare is around INR 50. The bus journey takes about 2 hours",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"Approximate road distance: 300 kilometers Road journey duration: Approximately 5 hours",
        d4train:"There are no direct trains from Kanyakumari to Ooty. You will have to take a train to Coimbatore and then change trains to Ooty. The total journey time is about 6 hours.",
        d4air:"There is no airport in Ooty. The nearest airport is Coimbatore International Airport, which is about 120 kilometers away. There are several flights from Coimbatore International Airport to Coimbatore Airport. The flight time is about 1 hour. From Coimbatore Airport, you can take a taxi or bus to Ooty. The taxi fare is around INR 200 and the bus fare is around INR 50. The bus journey takes about 2 hours.",
        d5trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"Approximate road distance: 300 kilometers Road journey duration: Approximately 5 hours",
        d5train:"There are several trains that travel from Kanyakumari to Kumbakonam. The fastest train is the Kanyakumari Express, which takes about 4 hours.",
        d5air:"There is no airport in Kumbakonam. The nearest airport is Trichy International Airport, which is about 120 kilometers away. There are several flights from Trichy International Airport to Madurai Airport. The flight time is about 1 hour. From Madurai Airport, you can take a taxi or bus to Kumbakonam. The taxi fare is around INR 200 and the bus fare is around INR 50. The bus journey takes about 2 hours.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"Approximate road distance: 630 kilometers Road journey duration: Approximately 10 hours",
        d6train:"There are several trains that travel from Kanyakumari to Madurai. The fastest train is the Kanyakumari Express, which takes about 8 hours.",
        d6air:"There is no airport in Madurai. The nearest airport is Madurai International Airport, which is about 120 kilometers away. There are several flights from Madurai International Airport to Madurai Airport. The flight time is about 1 hour.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Approximate road distance: 400 kilometers Road journey duration: Approximately 7 hours",
        d7train:"There are no direct trains from Kanyakumari to Yercaud. You will have to take a train to Salem and then change trains to Yercaud. The total journey time is about 9 hours.",
        d7air:"There is no airport in Yercaud. The nearest airport is Coimbatore International Airport, which is about 160 kilometers away. There are several flights from Coimbatore International Airport to Madurai Airport. The flight time is about 1 hour. From Madurai Airport, you can take a taxi or bus to Yercaud. The taxi fare is around INR 200 and the bus fare is around INR 50. The bus journey takes about 2 hours.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:"Approximate road distance: 350 kilometers Road journey duration: Approximately 6 hours",
        d8train:"There are no direct trains from Kanyakumari to Theni. You will have to take a train to Madurai and then change trains to Theni. The total journey time is about 8 hours.",
        d8air:"There is no airport in Thenni. The nearest airport is Madurai International Airport, which is about 150 kilometers away. There are several flights from Madurai International Airport to Madurai Airport. The flight time is about 1 hour. From Madurai Airport, you can take a taxi or bus to Thenni. The taxi fare is around INR 200 and the bus fare is around INR 50. The bus journey takes about 2 hours.",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"Approximate road distance: 450 kilometers Road journey duration: Approximately 8 hours",
        d9train:"There are no direct trains from Kanyakumari to Hogenakkal. You will have to take a train to Salem and then change trains to Hogenakkal. The total journey time is about 10 hours.",
        d9air:"There is no airport in Hogenakkal. The nearest airport is Salem International Airport, which is about 70 kilometers away. There are several flights from Salem International Airport to Madurai Airport. The flight time is about 1 hour. From Madurai Airport, you can take a taxi or bus to Hogenakkal. The taxi fare is around INR 200 and the bus fare is around INR 50. The bus journey takes about 2 hours",
    },
    {
        id:8,
        title:"Yercaud to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Kodaikanal","Ooty","Kumbakonam","Kanyakumar","Madurai","Theni","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"The distance between Yercaud and Chennai is 270 kilometers. The travel time is approximately 5 hours by car. The road is well-maintained and there are several rest stops along the way.",
        d1train:"There is no direct train from Yercaud to Chennai. The closest train station is at Salem, which is approximately 100 kilometers away. The travel time from Salem to Chennai is approximately 2 hours by train.",
        d1air:"The nearest airport is at Salem, which is approximately 100 kilometers away. There are several flights daily from Salem to Chennai. The flight time is approximately 30 minutes.",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:" The distance between Yercaud and Rameswaram is 600 kilometers. The travel time is approximately 10 hours by car. The road is well-maintained, but there are some sections that are hilly.",
        d2train:"There is no direct train from Yercaud to Rameswaram. The closest train station is at Salem, which is approximately 100 kilometers away. The travel time from Salem to Rameswaram is approximately 12 hours by train",
        d2air:"The nearest airport is at Madurai, which is approximately 150 kilometers away. There are several flights daily from Madurai to Rameswaram. The flight time is approximately 1 hour",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"The distance between Yercaud and Kodaikanal is 100 kilometers. The travel time is approximately 2 hours by car. The road is well-maintained and there are several scenic spots along the way.",
        d3train:"There is no direct train from Yercaud to Kodaikanal. The closest train station is at Coimbatore, which is approximately 150 kilometers away. The travel time from Coimbatore to Kodaikanal is approximately 4 hours by train.",
        d3air:"The nearest airport is at Coimbatore, which is approximately 150 kilometers away. There are several flights daily from Coimbatore to Kodaikanal. The flight time is approximately 30 minutes.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"The distance between Yercaud and Ooty is 120 kilometers. The travel time is approximately 2 hours by car. The road is well-maintained and there are several scenic spots along the way.",
        d4train:"There is no direct train from Yercaud to Ooty. The closest train station is at Coimbatore, which is approximately 150 kilometers away. The travel time from Coimbatore to Ooty is approximately 4 hours by train.",
        d4air:"The nearest airport is at Coimbatore, which is approximately 150 kilometers away. There are several flights daily from Coimbatore to Ooty. The flight time is approximately 30 minutes.",
        d5trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"The distance between Yercaud and Kumbakonam is 200 kilometers. The travel time is approximately 4 hours by car. The road is well-maintained and there are several temples and historical sites along the way.",
        d5train:"There is no direct train from Yercaud to Kumbakonam. The closest train station is at Salem, which is approximately 100 kilometers away. The travel time from Salem to Kumbakonam is approximately 3 hours by train.",
        d5air:" The nearest airport is at Madurai, which is approximately 150 kilometers away. There are several flights daily from Madurai to Kumbakonam. The flight time is approximately 1 hour.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"The distance between Yercaud and Kanyakumari is 600 kilometers. The travel time is approximately 10 hours by car. The road is well-maintained, but there are some sections that are hilly.",
        d6train:" There is no direct train from Yercaud to Kanyakumari. The closest train station is at Madurai, which is approximately 150 kilometers away. The travel time from Madurai to Kanyakumari is approximately 12 hours by train.",
        d6air:"The nearest airport is at Madurai, which is approximately 150 kilometers away. There are several flights daily from Madurai to Kanyakumari. The flight time is approximately 1 hour.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Yercaud to Madurai: The distance between Yercaud and Madurai is 125 kilometers. The road condition is good and the journey takes about 2 hours. There are several buses plying between the two cities, including government buses and private buses. The fare is around Rs 100 per person.",
        d7train:" There is no direct train from Yercaud to Madurai. You will have to take a train to Salem and then change trains to Madurai. The journey time from Salem to Madurai is about 2 hours. The fare for a second class seat is around Rs 100..",
        d7air:"There are no direct flights from Yercaud to Madurai, Theni, or Hogenakkal. You will need to fly to Coimbatore International Airport (CJB) and then take a connecting flight or bus to your destination.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:" The distance between Yercaud and Theni is 100 kilometers (62 miles). The road condition is good and the journey time is about 1.5 hours. There are many buses plying between Yercaud and Theni, and the fare is around Rs 80. You can also take a taxi, which will cost around Rs 150.",
        d8train:"Yercaud to Theni: There is no direct train from Yercaud to Theni. You will have to take a train to Salem and then change trains to Theni. The journey time from Salem to Theni is about 1.5 hours. The fare for a second class seat is around Rs 80.",
        d8air:" There is no airport in Yercaud, so you cannot travel to Theni by air. The nearest airport is the Salem Airport, which is about 90 kilometers away from Yercaud. You can take a taxi or bus from Salem Airport to Theni. The taxi fare will be around INR 1,500 and the bus fare will be around INR 150. The journey time by taxi is about 2 hours and the journey time by bus is about 3 hours.",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"Yercaud to hogenakkal: The distance between Yercaud and hogenakkal is 60 kilometers (37 miles). The road condition is good and the journey time is about 1 hour. There are many buses plying between Yercaud and hogenakkal, and the fare is around Rs 50. You can also take a taxi, which will cost around Rs 100.",
        d9train:"Yercaud to hogenakkal: There is no direct train from Yercaud to hogenakkal. You will have to take a train to Salem and then change trains to hogenakkal. The journey time from Salem to hogenakkal is about 1 hour. The fare for a second class seat is around Rs 50.",
        d9air:"There is no airport in Yercaud, so you cannot travel from Yercaud to Hogenakkal by air. The nearest airport is Salem Airport, which is about 65 kilometers away from Yercaud. From Salem Airport, you can take a taxi or bus to Hogenakkal. The taxi fare will be around INR 1500 and the bus fare will be around INR 100. The journey time by taxi will be about 1.5 hours and the journey time by bus will be about 2 hours.",
    },
    {
        id:9,
        title:"Theni to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Kodaikanal","Ooty","Kumbakonam","Madurai","Kanyakumari","Yercaud","Hogenakkal"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"The distance between Thenni and Chennai is about 450 kilometers. The journey by road takes about 8 hours. There are several express buses that run between Thenni and Chennai, including the SETC (State Express Transport Corporation) bus.",
        d1train:"The nearest train station to Thenni is the Madurai Junction railway station. There are several trains that run between Madurai and Chennai, including the Chennai Express, the Bangalore Express, and the Tirupati Express. The journey takes about 3 hours",
        d1air:"The nearest airport to Thenni is the Madurai International Airport. There are several airlines that operate flights between Madurai and Chennai, including Air India, IndiGo, and SpiceJet. The journey takes about 30 minutes.",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"The distance between Thenni and Rameshwaram is about 250 kilometers. The journey by road takes about 5 hours. There are several express buses that run between Thenni and Rameshwaram, including the SETC bus.",
        d2train:"There are also several trains that run between Madurai and Rameshwaram, including the Rameshwaram Express, the Thiruvarur Express, and the Madurai-Rameswaram passenger. The journey takes about 4 hours.",
        d2air:"There are also several airlines that operate flights between Madurai and Rameshwaram, including Air India, IndiGo, and SpiceJet. The journey takes about 45 minutes.",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"The distance between Thenni and Kodaikanal is about 150 kilometers. The journey by road takes about 3 hours. There are several express buses that run between Thenni and Kodaikanal, including the SETC bus.",
        d3train:"There are no direct trains from Madurai to Kodaikanal or Ooty. The nearest train station to Kodaikanal is the Kodaikanal Town railway station. There are several trains that run between Madurai and Kodaikanal, including the Madurai-Chennai passenger, the Madurai-Trichy passenger, and the Madurai-Palakkad passenger. The journey takes about 6 hours.",
        d3air:"There are no direct flights from Madurai to Kodaikanal or Ooty. The nearest airport to Kodaikanal is the Coimbatore International Airport. There are several airlines that operate flights between Madurai and Coimbatore, including Air India, IndiGo, and SpiceJet. The journey takes about 45 minutes.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"The distance between Thenni and Ooty is about 200 kilometers. The journey by road takes about 4 hours. There are several express buses that run between Thenni and Ooty, including the SETC bus.",
        d4train:"The nearest train station to Kumbakonam is the Kumbakonam railway station. There are several trains that run between Madurai and Kumbakonam, including the Chennai Express, the Bangalore Express, and the Tirupati Express. The journey takes about 2 hours",
        d4air:"There is no direct flight from Theni to Ooty. The nearest airport to Ooty is Coimbatore International Airport, which is about 70 kilometers away. There are a few airlines that fly from Theni to Coimbatore, including Air India, SpiceJet, and IndiGo. The flight takes about 1 hour. From Coimbatore, you can take a taxi or bus to Ooty. The taxi fare is around INR 1,500 and the bus fare is around INR 100. The total travel time from Theni to Ooty by air and taxi is about 2 hours 30 minutes.",
        d5trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"The distance between Thenni and Kumbakonam is about 150 kilometers. The journey by road takes about 3 hours. There are several express buses that run between Thenni and Kumbakonam, including the SETC bus.",
        d5train:"Theni to Kumbakonam: The fastest train from Theni to Kumbakonam is the Intercity Express, which takes about 4 hours. There are also slower trains that take about 6 hours.",
        d5air:"There are no direct flights from Theni to Kumbakonam. The nearest airport to Kumbakonam is Tiruchirapalli International Airport (TRZ), which is about 70 kilometers away. There are several airlines that offer flights from Theni to Tiruchirapalli, including IndiGo, Air India, and SpiceJet. The flight time is approximately 1 hour 20 minutes. From Tiruchirapalli, you can take a taxi or bus to Kumbakonam. The taxi ride takes about 1 hour, and the bus ride takes about 2 hours.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"Theni to Madurai: The distance between Theni and Madurai is 180 kilometers. The road condition is good and the journey takes about 3 hours. You can take the NH7 highway to reach Madurai.",
        d6train:"Theni to Madurai: The fastest train from Theni to Madurai is the Madurai Express, which takes about 3 hours. There are also slower trains that take about 5 hours.",
        d6air:"There are no direct flights from Theni to Madurai. The nearest airport to Theni is Madurai Airport, which is about 71 kilometers away. The travel time by air from Theni to Madurai is about 30 minutes.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"Theni to Kanyakumari: The distance between Theni and Kanyakumari is 450 kilometers. The road condition is good and the journey takes about 9 hours. You can take the NH48 highway to reach Kanyakumari.",
        d7train:"Theni to Kanyakumari: The fastest train from Theni to Kanyakumari is the Kanyakumari Express, which takes about 9 hours. There are also slower trains that take about 12 hours.",
        d7air:"There is no direct flight from Theni to Kanyakumari. The nearest airport to Theni is Madurai Airport, which is about 100 kilometers away. The nearest airport to Kanyakumari is Thiruvananthapuram International Airport, which is about 213 kilometers away.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:"Theni to Yercaud: The distance between Theni and Yercaud is 150 kilometers. The road condition is good and the journey takes about 3 hours. You can take the SH18 highway to reach Yercaud.",
        d8train:"Theni to Yercaud: There is no direct train from Theni to Yercaud. You will have to take a train to Salem and then a connecting train to Yercaud. The total travel time is about 6 hours.",
        d8air:"There is no direct flight from Theni to Yercaud. You can take a flight to Coimbatore International Airport (IATA: CJB, ICAO: VOCB), which is about 120 kilometers from Yercaud. From Coimbatore Airport, you can take a taxi or bus to Yercaud. The taxi fare is around INR 1,500 and the bus fare is around INR 100. The journey time by taxi is about 2 hours and by bus is about 3 hours",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"Theni to Hogenakkal: The distance between Theni and Hogenakkal is 120 kilometers. The road condition is good and the journey takes about 2.5 hours. You can take the SH18 highway to reach Hogenakkal.",
        d9train:"Theni to Hogenakkal: There is no direct train from Theni to Hogenakkal. You will have to take a train to Tiruchirapalli and then a connecting train to Hogenakkal. The total travel time is about 5 hours.",
        d9air:"There is no direct flight from Theni to Hogenakkal. The nearest airport to Hogenakkal is Salem Airport, which is about 236 kilometers away. You can fly from Theni to Salem Airport, and then take a taxi or bus to Hogenakkal. The total travel time will be around 4 hours.",
    },
    {
        id:10,
        title:"Hogenakkal to",
        note:"It's important to note that travel times are approximate and can vary based on factors such as traffic, weather conditions, road conditions, and the specific mode of transportation you choose.",
        places:["Chennai","Rameshwaram","Kodaikanal","Ooty","Kumbakonam","Madurai","Kanyakumari","Yercaud","Theni"],
        d1roadhed:"By Road (Bus/Car)",
        d1trainhed:"By Train:",
        d1airhed:"By Air:",
        d1road:"The road distance between Hogenakkal and Chennai is 262 km. The journey takes about 5 hours 30 minutes by car or bus. The road is well-maintained and there are several tolls along the way. The best way to get to Chennai from Hogenakkal is to take the NH44 highway. This highway connects Hogenakkal to Chennai via Dharmapuri, Krishnagiri, and Tiruvannamalai.",
        d1train:"There is no direct train from Hogenakkal to Chennai. The nearest railway station is Dharmapuri, which is about 47 km away. From Dharmapuri, you can take a train to Chennai Central. The journey takes about 6 hours 30 minutes. There are several trains available every day.",
        d1air:"The nearest airport to Hogenakkal is the Bangalore International Airport, which is about 216 km away. From Bangalore, you can take a flight to Chennai International Airport. The flight takes about 1 hour 30 minutes. There are several flights available every day.",
        d2roadhed:"By Road (Bus/Car)",
        d2trainhed:"By Train:",
        d2airhed:"By Air:",
        d2road:"The road distance between Hogenakkal and Rameshwaram is 479 km. The journey takes about 10 hours by car or bus. The road is well-maintained and there are several tolls along the way. The best way to get to Rameshwaram from Hogenakkal is to take the NH44 highway. This highway connects Hogenakkal to Rameshwaram via Madurai, Sivaganga, and Ramanathapuram.",
        d2train:"There is no direct train from Hogenakkal to Rameshwaram. The nearest railway station is Dindigul, which is about 100 km away. From Dindigul, you can take a train to Rameshwaram. The journey takes about 11 hours. There are several trains available every day.",
        d2air:"The nearest airport to Hogenakkal is the Madurai Airport, which is about 348 km away. From Madurai, you can take a flight to Rameshwaram Airport. The flight takes about 1 hour. There are several flights available every day",
        d3roadhed:"By Road (Bus/Car)",
        d3trainhed:"By Train:",
        d3airhed:"By Air:",
        d3road:"The road distance between Hogenakkal and Kodaikanal is 528 km. The journey takes about 10 hours 30 minutes by car or bus. The road is well-maintained but can be winding and narrow in some places. The best way to get to Kodaikanal from Hogenakkal is to take the NH44 highway to Salem and then the SH87 highway to Kodaikanal.",
        d3train:"There is no direct train from Hogenakkal to Kodaikanal. The nearest railway station is Salem Junction, which is about 250 km away. From Salem, you can take a train to Kodaikanal. The journey takes about 6 hours. There are several trains available every day.",
        d3air:"The nearest airport to Hogenakkal is the Coimbatore Airport, which is about 469 km away. From Coimbatore, you can take a flight to Madurai Airport and then a taxi to Kodaikanal. The flight takes about 1 hour 30 minutes. There are several flights available every day.",
        d4roadhed:"By Road (Bus/Car)",
        d4trainhed:"By Train:",
        d4airhed:"By Air:",
        d4road:"The road distance between Hogenakkal and Ooty is 253 km. The journey takes about 6 hours by car or bus. The road is well-maintained but can be winding and narrow in some places. The best way to get to Ooty from Hogenakkal is to take the NH44 highway to Salem and then the SH81 highway to Ooty.",
        d4train:"There is no direct train from Hogenakkal to Ooty. The nearest railway station is Coimbatore Junction, which is about 272 km away. From Coimbatore, you can take a train to Ooty. The journey takes about 5 hours. There are several trains available every day",
        d4air:"The nearest airport to Hogenakkal is the Coimbatore Airport, which is about 272 km away. From Coimbatore, you can take a flight to Coimbatore Airport and then a taxi to Ooty. The flight takes about 1 hour 30 minutes. There are several flights available every day",
        d3trainhed:"By Train:",
        d5roadhed:"By Road (Bus/Car)",
        d5airhed:"By Air:",
        d5road:"The road distance between Hogenakkal and Kumbakonam is 341 km. The journey takes about 7 hours 30 minutes by car or bus. The road is well-maintained and there are several tolls along the way. The best way to get to Kumbakonam from Hogenakkal is to take the NH44 highway. This highway connects Hogenakkal to Kumbakonam via Dharmapuri, Krishnagiri, and Tiruchirapalli",
        d5train:"The nearest railway station to Hogenakkal is Dharmapuri, which is about 47 km away. From Dharmapuri, you can take a train to Kumbakonam Junction. The journey takes about 5 hours. There are several trains available every day.",
        d5air:"There is no airport near Hogenakkal. The nearest airport is the Tiruchirapalli International Airport, which is about 130 km away. From Tiruchirapalli, you can take a taxi to Kumbakonam. The taxi ride takes about 2 hours.",
        d6roadhed:"By Road (Bus/Car)",
        d6trainhed:"By Train:",
        d6airhed:"By Air:",
        d6road:"The road distance between Hogenakkal and Madurai is 117 km. The journey takes about 3 hours by car or bus. The road is well-maintained and there are several tolls along the way. The best way to get to Madurai from Hogenakkal is to take the NH44 highway. This highway connects Hogenakkal to Madurai via Dindigul. ",
        d6train:"The nearest railway station to Hogenakkal is Dharmapuri, which is about 47 km away. From Dharmapuri, you can take a train to Madurai Junction. The journey takes about 2 hours 30 minutes. There are several trains available every day.",
        d6air:"The nearest airport to Hogenakkal is the Madurai Airport, which is about 117 km away. From Madurai, you can take a taxi to Hogenakkal. The taxi ride takes about 1 hour.",
        d7roadhed:"By Road (Bus/Car)",
        d7trainhed:"By Train:",
        d7airhed:"By Air:",
        d7road:"The road distance between Hogenakkal and kanyakumari is 586 km. The journey takes about 10 hours 30 minutes by car or bus. The road is well-maintained but can be winding and narrow in some places. The best way to get to kanyakumari from Hogenakkal is to take the NH44 highway to Madurai and then the NH744 highway to kanyakumari. ",
        d7train:"There is no direct train from Hogenakkal to kanyakumari. The nearest railway station is Madurai Junction, which is about 117 km away. From Madurai, you can take a train to kanyakumari. The journey takes about 11 hours. There are several trains available every day.",
        d7air:"The nearest airport to Hogenakkal is the Madurai Airport, which is about 117 km away. From Madurai, you can take a flight to Thiruvananthapuram International Airport and then a taxi to kanyakumari. The flight takes about 1 hour. There are several flights available every day.",
        d8roadhed:"By Road (Bus/Car)",
        d8trainhed:"By Train:",
        d8airhed:"By Air:",
        d8road:"The road distance between Hogenakkal and yecaud is 283 km. The journey takes about 5 hours 30 minutes by car or bus. The road is well-maintained and there are several tolls along the way. The best way to get to yecaud from Hogenakkal is to take the NH44 highway to Salem and then the SH87 highway to yecaud. ",
        d8train:"There is no direct train from Hogenakkal to yecaud. The nearest railway station is Salem Junction, which is about 250 km away. From Salem, you can take a train to yecaud. The journey takes about 4 hours. There are several trains available every day.",
        d8air:"The nearest airport to Hogenakkal is the Coimb",
        d9roadhed:"By Road (Bus/Car)",
        d9trainhed:"By Train:",
        d9airhed:"By Air:",
        d9road:"The road distance between Hogenakkal and Theni is 153 km. The journey takes about 3 hours by car or bus. The road is well-maintained and there are several tolls along the way. The best way to get to Theni from Hogenakkal is to take the NH44 highway. This highway connects Hogenakkal to Theni via Dindigul and Madurai",
        d9train:"There is no direct train from Hogenakkal to Theni. The nearest railway station is Dindigul Junction, which is about 100 km away. From Dindigul, you can take a train to Theni. The journey takes about 2 hours. There are several trains available every day.",
        d9air:"The nearest airport to Hogenakkal is the Madurai Airport, which is about 117 km away. From Madurai, you can take a taxi to Theni. The taxi ride takes about 2 hours.",
    }
   

]

export default datapackege;